homeassistant:
  # Name of the location where Home Assistant is running
  name: Sroda
  # Location required to calculate the time the sun rises and sets
  latitude: 52.23552
  longitude: 17.2682163
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 86
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Warsaw
  # Customization file
  customize: !include customize.yaml

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  # Secrets are defined in the file secrets.yaml
  # api_password: !secret http_password
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  # base_url: example.duckdns.org:8123

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
#conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Weather prediction
#sensor:
#  - platform: yr

sensor:
  - platform: yr
    name: Weather
    forecast: 24
    monitored_conditions:
      - temperature
      - symbol
      - precipitation
      - windSpeed
      - pressure
#      - windDirection
#     - humidity
#     - fog
#     - cloudiness
#     - lowClouds
#     - mediumClouds
#     - highClouds
#     - dewpointTemperature

# Text to speech
#tts:
#  - platform: google

# Cloud
#cloud:

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml

#panel_iframe:
#  configurator:
#    title: Configurator
#    icon: mdi:wrench
#    url: http://hassio.local:3218

vacuum:
  - platform: xiaomi_miio
    host: 192.168.1.114
    name: zmietek
    token: !secret xiaomi_miio_token

xiaomi_aqara:
# interface: '192.168.1.113'
  discovery_retry: 10
  gateways:
    - key: !secret xiaomi_aqara_key
#     mac: 78:11:dc:fa:2e:b9

light:
  - platform: yeelight
    devices:
      192.168.1.105:
        name: 'Kuchnia LED'
        use_music_mode: False
      192.168.1.120:
        name: 'Kuchnia Lampa'

notify:
  - name: mypushbullet
    platform: pushbullet
    api_key: !secret pushbullet_api_key

device_tracker:
  - platform: fritz
    host: 192.168.1.108
    password: !secret fritxbox_password
